### ISSUE TITLE
Replacing the z80 emulator in Collapse OS?

### ISSUE THREAD

**Issue by ghost** [schierlm/CollapseOS-Web-Emulator#1]
I was playing around with your Forth VM and I noticed that it was much faster than the default z80 emulator that is the centerpiece of Collapse OS on a POSIX machine. This gave me an idea: what if we replaced `/emul/forth` and `/emul/stage` with programs wrapping mujs (or some other minimal JS interpreter) and plugged your JS VM in it. Do you think it could work? Do you see blockers?

**Comment by ghost** [comment]
Or maybe it would be easier to go straight to "C VM"...

**Comment by schierlm** [comment]
Heh, we must have similar minds. When reading your first comment, my first reaction was to instead port the JS vm to C (or Rust or any other LLVM-compiled language). That way, you get faster bootstrapping and you also get support for architectures that have a cross-target for LLVM or gcc, but are too small to self-host a C compiler (thinking of ESP8266) "almost for free".

About speed of bootstrapping/compiling: I also noticed that my bootstrap.js is orders of magnitude faster than using the JavaScript forth VM, in the same browser (7 ms vs 700 ms on my machine). I have some suspicion where that comes from and when I am right, the compilation can be speeded up considerably by adding about 5 "blocks" of platform-independent Forth code, and consuming ~1KB more memory during compilation (resulting in identical binaries of course). But I'll have to test my hypothesis first, perhaps I am completely wrong and may sound like a fool :)

**Comment by schierlm** [comment]
Also, I don't believe the JavaScript performance of mujs is anywhere near comparable to Google's V8 or Mozilla's SpiderMonkey (in one of which you probably tested my Forth VM).

**Comment by ghost** [comment]
And now that I have that idea in my head, I can't get it out: I *have* to implement it :)

One clever idea I think I had for bootstrapping would be to have my C VM insert all native words at the exact same offset as the current z80 `forth.bin` (effectively treating all native words as a "stable ABI") in VM memory. I *think* that with this, I could get away with not having to re-implement xcomp in C like you did in `bootstrap.js` because I could `dd` the high part of `forth.bin` into my C bin. Once I have a running C VM, I can de-stablize native words and rebuild a compiled dict binary using Forth's xcomp unit.

I'm not sure at all that it's going to work, but I'm trying...

**Comment by schierlm** [comment]
`bootstrap.js` came later because I wanted more flexibility. First I compiled [this xcomp unit](https://github.com/schierlm/CollapseOS-Web-Emulator/blob/master/emul0-xcomp.fs) using your Z80 `stage`. That binary should not have any native offsets (native words are referenced by index) so should work in a C VM as-is, if your C VM also indexes native words by index.

But there are many ways that lead to Rome :)

Also, I would not mess with dd at first. Have two files (one binary file containing the c output, and one data file containing the Forth words) and let the binary file load the data file into memory.

**Comment by ghost** [comment]
It works! https://git.sr.ht/~vdupras/collapseos/commit/36cb138 Now I just need to make it build itself.
