### ISSUE TITLE
Unexpected behavior of either A> or >A or .S

### ISSUE THREAD

**Issue by cratuki** [schierlm/CollapseOS-Web-Emulator#2]
For these notes, I was using Emulator 0 (2022-08/emul0.html).

Here is an interaction,

![20240214_101926_m75-office-001_289x317](https://github.com/schierlm/CollapseOS-Web-Emulator/assets/5275325/c47d5673-e829-496f-ab05-c887670c8145)

Based on the notes in the collapseos documentation, I expected >A to put 5 into register A. Then, A> to append 5 to the stack. Rather, I get fe21 on the stack after A>.

Is there a bug in the emulator, or my understanding?

**Comment by schierlm** [comment]
The "bug" is in your understanding. As documented on page 19 of the [documentation](https://schierlm.github.io/CollapseOS-Web-Emulator/2022-08/collapseos.pdf), the A register is clobbered (i.e. not preserved) by all words that are annotated with `*A*` in documentation of that word. The word `.S` that you are using to introspect the system is marked with `*A*` (see page 31).

Therefore, by inspecting the system, you clobbered your A register and the value afterwards is in fact unspecified. It could be `fe21` or `1234` or `dead`, you cannot rely on it any longer.

**Comment by cratuki** [comment]
Michael - thanks for the fast response to this and for the detailed correction.

I had seen the *A* doc but overlooked that .S was affected.

I played with the situation some more. I found that the A register would go sour while I was in interactive mode, even if I did not do .S. Then I tried defining a word to modify A, and found I could retrieve the value with no problems.
